In [1]:
import numpy as np
np.__version__

'1.21.5'

In [5]:
np.array([1,2,45,67,7])

np.array([1,2,45,67,7.56])

array([ 1.  ,  2.  , 45.  , 67.  ,  7.56])

In [7]:
np.array([1,2,45,67,7.77],dtype='int32')

array([ 1,  2, 45, 67,  7])

In [11]:
np.array([input('please enter values:',lis[])],dtype='int32')

SyntaxError: invalid syntax (2631138052.py, line 1)

In [12]:
np.zeros(10,dtype='float32')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [13]:
np.ones((3,3),dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [16]:
np.arange(0,25,3,dtype='float')

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24.])

In [22]:
np.linspace(0,10,2)

array([ 0., 10.])

In [23]:
np.random.random((4,4))

array([[0.78863387, 0.10603927, 0.22768789, 0.82585628],
       [0.61661986, 0.17988052, 0.77001368, 0.44530441],
       [0.7627874 , 0.46866267, 0.34253086, 0.02580892],
       [0.68960035, 0.50374876, 0.92345105, 0.05599126]])

In [26]:
np.random.normal(0,1, (3,3))

array([[ 1.17809426, -0.37652412, -0.02766945],
       [-0.65712016,  0.0631619 , -0.05327348],
       [ 0.36511474, -0.82893119,  0.62422793]])

In [27]:
np.random.randint(0,10, (3,3))

array([[5, 0, 8],
       [1, 6, 0],
       [8, 6, 7]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
arr4=np.empty(4)
print(arr4)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 6.95208344e-310]


In [44]:
arr0=np.random.randint(20,size=(4,4))
print(arr0)

[[ 3  6 11 14]
 [18  0 14  3]
 [12 10 11  4]
 [ 6  4 15  3]]


In [45]:
arr1=np.random.randint(0,20,(4,4),)
print(arr1)

[[12  4  8 14]
 [15  3 15 13]
 [16 17  5  9]
 [ 3  0  5  0]]


In [46]:
#3d array means, how many row and colums array are there 
#in 
np.random.seed(0)
arr2=np.random.randint(0,20,(3,4,5))
print(arr2)

[[[12 15  0  3  3]
  [ 7  9 19 18  4]
  [ 6 12  1  6  7]
  [14 17  5 13  8]]

 [[ 9 19 16 19  5]
  [15 15  0 18  3]
  [17 19 19 19 14]
  [ 7  0  1  9  0]]

 [[10  3 11 18  2]
  [ 0  0  4  5  6]
  [ 8 17 15  4  9]
  [10  1  1  7  9]]]


In [48]:
arr1.shape

(4, 4)

In [49]:
arr1.ndim

2

In [50]:
arr2.size

60

In [51]:
arr2.dtype

dtype('int32')

In [52]:
arr2.itemsize

4

In [53]:
arr2.nbytes

240

In [54]:
arr2

array([[[12, 15,  0,  3,  3],
        [ 7,  9, 19, 18,  4],
        [ 6, 12,  1,  6,  7],
        [14, 17,  5, 13,  8]],

       [[ 9, 19, 16, 19,  5],
        [15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14],
        [ 7,  0,  1,  9,  0]],

       [[10,  3, 11, 18,  2],
        [ 0,  0,  4,  5,  6],
        [ 8, 17, 15,  4,  9],
        [10,  1,  1,  7,  9]]])

In [61]:
arr2[0:,[1,2]]

array([[[ 7,  9, 19, 18,  4],
        [ 6, 12,  1,  6,  7]],

       [[15, 15,  0, 18,  3],
        [17, 19, 19, 19, 14]],

       [[ 0,  0,  4,  5,  6],
        [ 8, 17, 15,  4,  9]]])

In [59]:
arr4[2]

1.6912109553714024e-306

In [62]:
#values can be modified using the list
arr2[0,0]=9

In [63]:
arr4[::2]

array([6.23042070e-307, 1.69121096e-306])

In [64]:
arr1[::2]

array([[12,  4,  8, 14],
       [16, 17,  5,  9]])

In [65]:
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr5[::2]

array([0, 2, 4, 6, 8])

In [67]:
arr5[::-2]

array([9, 7, 5, 3, 1])

In [69]:
arr5[2:-5]

array([2, 3, 4])

In [71]:
arr5[5::-2]

array([5, 3, 1])